-- AlterTable
ALTER TABLE "Booking" ADD COLUMN     "basePrice" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN     "serviceFee" DECIMAL(65,30) NOT NULL DEFAULT 0,
ALTER COLUMN "totalPrice" SET DEFAULT 0;
